package com.javaoutofbounds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-12-25T16:36:57.643Z
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "studentEndpointService", 
                  wsdlLocation = "file:/D:/JbossWorkSpace/SKP_1/camel-cxfsoap-service/src/main/resources/wsdl/students.wsdl",
                  targetNamespace = "http://www.javaoutofbounds.com") 
public class StudentEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.javaoutofbounds.com", "studentEndpointService");
    public final static QName StudentsEndpoint = new QName("http://www.javaoutofbounds.com", "studentsEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/JbossWorkSpace/SKP_1/camel-cxfsoap-service/src/main/resources/wsdl/students.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentEndpointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/JbossWorkSpace/SKP_1/camel-cxfsoap-service/src/main/resources/wsdl/students.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Students
     */
    @WebEndpoint(name = "studentsEndpoint")
    public Students getStudentsEndpoint() {
        return super.getPort(StudentsEndpoint, Students.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Students
     */
    @WebEndpoint(name = "studentsEndpoint")
    public Students getStudentsEndpoint(WebServiceFeature... features) {
        return super.getPort(StudentsEndpoint, Students.class, features);
    }

}
